### ISSUE TITLE
Clarify picked status

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/msupply_docs#12]
https://github.com/openmsupply/msupply_docs/blob/e8e75cc6bf630ea2877bf388ef5e41904f642bd4/content/docs/distribution/outbound_shipments.fr.md#L214

Good are actually not part of the inventory at this stage, as per API docs:

![Screenshot 2023-09-29 at 10 53 06 AM](https://github.com/openmsupply/msupply_docs/assets/26194949/573725f1-4a9f-4b6f-9465-6d91db313681)

**Comment by andreievg** [comment]
Also comment from @Chris-Petty 

> Ooooh See in the oms docs "New" doesn't mention "Goods are no longer available" I didn't realise it took affect straight away

**Comment by roxy-dao** [comment]
Can I bump this please @richardmoizeau

**Comment by richardmoizeau** [comment]
Indeed, picked stocklines should still be part of the in-store stock (not SOH). What was implemented in Open mSupply ? Is it just a mistake from the docs ?

**Comment by roxy-dao** [comment]
Current behaviour is: Picked: Stock is no longer part of inventory. Delivered: Stock is part of inventory and can be used.

**Comment by andreievg** [comment]
I lost all context for this issue (it was created awhile ago). I was wondering what was being clarified, and what are the clarifications refering do ? 
What is 'in-store stock' (we have available stock and total stock as terms, available means in store and not reserved, unavailable = in store and reserver, total = not in store) ?

Are we talking Outbound Shipments, or Inbound Shipments ?

**Comment by roxy-dao** [comment]
Update in docs will push soon.
