### ISSUE TITLE
A diagram for different flavours of omSupply and how/where they work

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/msupply_docs#42]
During one of our testing meetings, and in the context of [this bug](https://github.com/msupply-foundation/open-msupply/issues/3966), there seems to be some miscom about different flavours of omSupply, and in which context they are used. 
I think an overall diagram might help with this, and i feel like we had this diagram ?

**Comment by mark-prins** [comment]
A diagram is on [google drive](https://docs.google.com/document/d/11bhVlu4zXpc7yQl5nUSjej-LCUyJM9rWh4HWHQOFQO4/edit)
